---
- hosts: 172.31.36.187
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname
    register: myresult

  - name: display first task result
    debug:
      msg: "{{mresult}}"

       