---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to ping all nodes
    ping:

  - name: i want to install webserver on ubuntu node
    apt:
     name: "{{myubuntuwebpackage}}"
     state: present
    when: ansible_os_family=="Debian" 

  - name: i want to start webserver
    service:
     name: "{{myubuntuwebpackage}}"
     state: started
    when: ansible_os_family=="Debian"

  
  - name: i want to install webserver on RedHatnode only
    yum:
     name: "{{myredhatwebpackage}}"
     state: present
    when: ansible_os_family=="RedHat" 

  - name: i want to start webserver on RedHatnode only
    service:
     name: "{{myredhatwebpackage}}"
     state: started
    when: ansible_os_family=="RedHat"