---
- hosts: 172.31.4.221
  become: yes
  tasks:

  - name: i want to install webserver on RedHatnode only
    yum:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat" 

  - name: i want to start webserver on RedHatnode only
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"
